# Generated by Django 4.0.4 on 2022-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(default='default.png', upload_to='media'),
            preserve_default=False,
        ),
    ]
