# Generated by Django 4.0.4 on 2022-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
