# Generated by Django 4.0.4 on 2022-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_course_owner_alter_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_courses', models.IntegerField(default=0)),
                ('number_of_teachers', models.IntegerField(default=0)),
                ('number_of_students', models.IntegerField(default=0)),
            ],
        ),
    ]
