# Generated by Django 4.0.4 on 2022-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_statistics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
